"""add is_active soft delete to exercises and exercise_categories

Revision ID: 349c552be1f5
Revises: 547be2ed9516
Create Date: 2026-08-22 16:18:31.907346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349c552be1f5'
down_revision = '547be2ed9516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('body_metrics_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('exercise_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    with op.batch_alter_table('exercise_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exercise_favorites_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('exercise_favorites_exercise_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
        batch_op.drop_constraint(batch_op.f('exercises_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercise_categories', ['category_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transcript_chunks_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transcript_chunks_video_id_fkey'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exercises_category_id_fkey'), 'exercise_categories', ['category_id'], ['id'])
        batch_op.drop_column('is_active')

    with op.batch_alter_table('exercise_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exercise_favorites_exercise_id_fkey'), 'exercises', ['exercise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('exercise_favorites_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('exercise_categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('body_metrics_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
