"""create exercise_favorites table

Revision ID: 547be2ed9516
Revises: d3ad5ce8b8f3
Create Date: 2026-08-22 13:54:14.485796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547be2ed9516'
down_revision = 'd3ad5ce8b8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['public.exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_user_exercise_favorite'),
    schema='public'
    )
    with op.batch_alter_table('exercise_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_exercise_favorites_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_exercise_favorites_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('body_metrics_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exercises_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercise_categories', ['category_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transcript_chunks_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transcript_chunks_video_id_fkey'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exercises_category_id_fkey'), 'exercise_categories', ['category_id'], ['id'])

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('body_metrics_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('exercise_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_exercise_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_public_exercise_favorites_exercise_id'))

    op.drop_table('exercise_favorites', schema='public')
    # ### end Alembic commands ###
