"""Add progress_analyses table for rate limiting

Revision ID: 2ae982b570ac
Revises: a3828d880ae1
Create Date: 2026-08-26 13:08:17.799470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae982b570ac'
down_revision = 'a3828d880ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('progress_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_progress_analyses_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('body_metrics_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('exercise_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exercise_favorites_exercise_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('exercise_favorites_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exercises_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercise_categories', ['category_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transcript_chunks_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transcript_chunks_video_id_fkey'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exercises_category_id_fkey'), 'exercise_categories', ['category_id'], ['id'])

    with op.batch_alter_table('exercise_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exercise_favorites_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('exercise_favorites_exercise_id_fkey'), 'exercises', ['exercise_id'], ['id'])

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('body_metrics_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('progress_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_progress_analyses_user_id'))

    op.drop_table('progress_analyses', schema='public')
    # ### end Alembic commands ###
