"""create feedback table

Revision ID: 52e6ac9de68b
Revises: 2ae982b570ac
Create Date: 2026-08-28 12:55:10.693044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e6ac9de68b'
down_revision = '2ae982b570ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_feedback_user_id'), ['user_id'], unique=False)

    # Nota: se removieron a mano varios bloques que autogenerate agrego aca -
    # detecto una diferencia cosmetica entre como quedaron creadas las FK de
    # body_metrics/exercise_favorites/exercises/progress_analyses/transcript_chunks
    # originalmente y como las describe el metadata de SQLAlchemy hoy
    # (referent_schema explicito), pero el constraint real es identico. No
    # tiene sentido hacer drop+create de FKs en tablas con datos reales por
    # una diferencia que no cambia el comportamiento.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_feedback_user_id'))

    op.drop_table('feedback', schema='public')
    # ### end Alembic commands ###
