"""create body_regions and link exercise_categories

Revision ID: 73783385e917
Revises: 52e6ac9de68b
Create Date: 2026-08-29 01:19:25.671703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73783385e917'
down_revision = '52e6ac9de68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )

    with op.batch_alter_table('exercise_categories', schema=None) as batch_op:
        #nullable=True aca a proposito, aunque el modelo lo declara nullable=False: ya existe
        #una fila ("Pecho") sin este valor, asi que no se puede agregar la columna como
        #NOT NULL de una. El endurecimiento a NOT NULL, despues de rellenar los datos, va en
        #la siguiente migracion (require_body_region_on_categories).
        batch_op.add_column(sa.Column('body_region_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_public_exercise_categories_body_region_id'), ['body_region_id'], unique=False)
        batch_op.create_foreign_key(None, 'body_regions', ['body_region_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###
    # Nota: se removieron a mano varios bloques que autogenerate agrego aca - detecto una
    # diferencia cosmetica de como quedaron creadas las FK de otras tablas (que no tocamos)
    # originalmente vs. como las describe el metadata de SQLAlchemy hoy (referent_schema
    # explicito). Mismo caso que en la migracion de la tabla feedback.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_public_exercise_categories_body_region_id'))
        batch_op.drop_column('body_region_id')

    op.drop_table('body_regions', schema='public')
    # ### end Alembic commands ###
