"""require body_region_id on exercise_categories

Revision ID: 98514a83802d
Revises: 73783385e917
Create Date: 2026-08-29 01:20:40.619219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98514a83802d'
down_revision = '73783385e917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_categories', schema=None) as batch_op:
        batch_op.alter_column('body_region_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
    # Nota: se removio el resto (drop/create de FKs en tablas que no tocamos, incluida la
    # propia FK de body_region_id que no cambia) - mismo ruido cosmetico de autogenerate que
    # en migraciones anteriores.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_categories', schema=None) as batch_op:
        batch_op.alter_column('body_region_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
