"""Add google_id, avatar_url; relax user fields for Google SSO

Revision ID: a3828d880ae1
Revises: 349c552be1f5
Create Date: 2026-08-25 21:24:12.372366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3828d880ae1'
down_revision = '349c552be1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('body_metrics_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('exercise_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exercise_favorites_exercise_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('exercise_favorites_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exercises_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercise_categories', ['category_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transcript_chunks_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transcript_chunks_video_id_fkey'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exercises_category_id_fkey'), 'exercise_categories', ['category_id'], ['id'])

    with op.batch_alter_table('exercise_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exercise_favorites_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('exercise_favorites_exercise_id_fkey'), 'exercises', ['exercise_id'], ['id'])

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('body_metrics_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
