"""create exercise_categories and exercises tables

Revision ID: d3ad5ce8b8f3
Revises: ff69e97bbd52
Create Date: 2026-08-20 02:28:15.247310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ad5ce8b8f3'
down_revision = 'ff69e97bbd52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['public.exercise_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_category_exercise_name'),
    schema='public'
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_exercises_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('body_metrics_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transcript_chunks_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transcript_chunks_video_id_fkey'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('body_metrics_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_exercises_category_id'))

    op.drop_table('exercises', schema='public')
    op.drop_table('exercise_categories', schema='public')
    # ### end Alembic commands ###
