"""create body_metrics table

Revision ID: ff69e97bbd52
Revises: 91e542a485a7
Create Date: 2026-08-20 00:28:03.557953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff69e97bbd52'
down_revision = '91e542a485a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('muscle_mass_percentage', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_body_metrics_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transcript_chunks_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transcript_chunks_video_id_fkey'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_body_metrics_user_id'))

    op.drop_table('body_metrics', schema='public')
    # ### end Alembic commands ###
